/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutPlanRouteImport } from './routes/workout-plan'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProteinCalculatorRouteImport } from './routes/protein-calculator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutPlanRoute = WorkoutPlanRouteImport.update({
  id: '/workout-plan',
  path: '/workout-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteinCalculatorRoute = ProteinCalculatorRouteImport.update({
  id: '/protein-calculator',
  path: '/protein-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/protein-calculator': typeof ProteinCalculatorRoute
  '/signup': typeof SignupRoute
  '/workout-plan': typeof WorkoutPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/protein-calculator': typeof ProteinCalculatorRoute
  '/signup': typeof SignupRoute
  '/workout-plan': typeof WorkoutPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/meal-plan': typeof MealPlanRoute
  '/onboarding': typeof OnboardingRoute
  '/protein-calculator': typeof ProteinCalculatorRoute
  '/signup': typeof SignupRoute
  '/workout-plan': typeof WorkoutPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/protein-calculator'
    | '/signup'
    | '/workout-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/protein-calculator'
    | '/signup'
    | '/workout-plan'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/login'
    | '/meal-plan'
    | '/onboarding'
    | '/protein-calculator'
    | '/signup'
    | '/workout-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MealPlanRoute: typeof MealPlanRoute
  OnboardingRoute: typeof OnboardingRoute
  ProteinCalculatorRoute: typeof ProteinCalculatorRoute
  SignupRoute: typeof SignupRoute
  WorkoutPlanRoute: typeof WorkoutPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout-plan': {
      id: '/workout-plan'
      path: '/workout-plan'
      fullPath: '/workout-plan'
      preLoaderRoute: typeof WorkoutPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protein-calculator': {
      id: '/protein-calculator'
      path: '/protein-calculator'
      fullPath: '/protein-calculator'
      preLoaderRoute: typeof ProteinCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MealPlanRoute: MealPlanRoute,
  OnboardingRoute: OnboardingRoute,
  ProteinCalculatorRoute: ProteinCalculatorRoute,
  SignupRoute: SignupRoute,
  WorkoutPlanRoute: WorkoutPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
